DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS inquiries CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS product_categories CASCADE;
DROP TABLE IF EXISTS buyer_profiles CASCADE;
DROP TABLE IF EXISTS farmer_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  phone VARCHAR(30) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'farmer', 'buyer')),
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE farmer_profiles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE,
  farm_name VARCHAR(150) NOT NULL,
  farm_description TEXT,
  district VARCHAR(100) NOT NULL,
  subcounty VARCHAR(100),
  village VARCHAR(100),
  address VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_farmer_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE buyer_profiles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE,
  buyer_type VARCHAR(80) NOT NULL,
  business_name VARCHAR(150),
  district VARCHAR(100) NOT NULL,
  address VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_buyer_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE product_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farmer_id INTEGER NOT NULL,
  category_id INTEGER NOT NULL,
  product_name VARCHAR(150) NOT NULL,
  description TEXT,
  quantity NUMERIC(10, 2) NOT NULL,
  unit VARCHAR(40) NOT NULL,
  price_per_unit NUMERIC(10, 2) NOT NULL,
  district VARCHAR(100) NOT NULL,
  location_details VARCHAR(255),
  image VARCHAR(255),
  harvest_date DATE,
  availability_status VARCHAR(20) NOT NULL DEFAULT 'available' CHECK (availability_status IN ('available', 'sold_out', 'inactive')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_product_farmer FOREIGN KEY (farmer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES product_categories(id)
);

CREATE TABLE orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_id INTEGER NOT NULL,
  farmer_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  quantity_requested NUMERIC(10, 2) NOT NULL,
  total_estimated_price NUMERIC(12, 2) NOT NULL,
  delivery_option VARCHAR(80) NOT NULL,
  buyer_message TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'completed', 'cancelled')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_order_buyer FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_farmer FOREIGN KEY (farmer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE inquiries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_id INTEGER NOT NULL,
  farmer_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  message TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'answered', 'closed')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inquiry_buyer FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_inquiry_farmer FOREIGN KEY (farmer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_inquiry_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE favorites (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_favorite UNIQUE (buyer_id, product_id),
  CONSTRAINT fk_favorite_buyer FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_favorite_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER,
  action VARCHAR(150) NOT NULL,
  details TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER farmer_profiles_set_updated_at
BEFORE UPDATE ON farmer_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER buyer_profiles_set_updated_at
BEFORE UPDATE ON buyer_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER product_categories_set_updated_at
BEFORE UPDATE ON product_categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER products_set_updated_at
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER orders_set_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER inquiries_set_updated_at
BEFORE UPDATE ON inquiries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();


--  Selected Feature (Logistics Opperator Role )
-- A logistics operator acts as a hired service provider for freiht between a 
-- farmer and the buyer, they can fulfill orders on behalf of the farmer or buyer

-- Logistics Operator Profile Table

CREATE TABLE logistics_operator_profiles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id INTEGER NOT NULL UNIQUE,

  opp_name VARCHAR(150) NOT NULL,
  opp_description TEXT,
  district VARCHAR(100) NOT NULL,
  subcounty VARCHAR(100),
  village VARCHAR(100),
  address VARCHAR(255),
  vehicle VARCHAR(255),
  max_tonnage INTEGER NOT NULL,


  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_logistics_opp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Frieght Orders Table

CREATE TABLE freight_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  buyer_id INTEGER,
  opp_id INTEGER NOT NULL,
  order_id INTEGER NOT NULL,
  farmer_id INTEGER NOT NULL,

  order_destination VARCHAR(256) NOT NULL,
  tonnage INTEGER NOT NULL,


  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_freight_order_user FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE CASCADE
  CONSTRAINT fk_freight_order_logistics_opp FOREIGN KEY (opp_id) REFERENCES logistics_operator_profiles(id) ON DELETE CASCADE
  CONSTRAINT fk_freight_order_farmer FOREIGN KEY (farmer_id) REFERENCES farmer_profiles(id) ON DELETE CASCADE
  CONSTRAINT fk_freight_order__orders FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE

);

-- Relevant Table Mutation

-- users table

ALTER TABLE users DROP CONSTRAINT users_role_check; -- drop active CHECK
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('admin','farmer','buyer', 'logistics')); -- Add new CHECK
